# -*- coding: utf-8 -*-
"""nomor1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-9LkV1GjU69aezjVjTqOm6c-_FcPP2Dq
"""

# Rafie Mirza Ramadhan - 21091397037
# No. 1A

#single perceptron, single neuron

#memulai numpy
import numpy as np

#memasukkan variabel yang diinginkan
inputs = [1.0, 2.0, 1.5, 4.2, 6.0, 7.4, 2.1, 1.3, 6.1, 3.7]
weights = [-1.2, 3.5, 5.3, 7.2, -3.1, 8.0, 1.4, 7.3, 9.9, 5.1]
bias = 4.0

#proses perhitungan output
output = np.dot(weights, inputs) + bias

#pemanggilan output
print(output)