# -*- coding: utf-8 -*-
"""nomor1c.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W0-q4x-DArFINaspbQNj7LoM8RX9s3p7
"""

# Rafie Mirza Ramadhan - 21091397037
# No. 1C

#multi perceptron, neuron batch

import numpy as np

#memasukkan variabel yang diinginkan 
inputs = [[9.2, 8.1, 6.7, 1.3, 7.4, 2.1, 6.1, 3.7, 9.1, 1.0],
          [1.2, 2.2, 3.2, 4.6, 6.5, 7.0, 9.9, 1.7, 7.9, 3.0],
          [6.6, 0.3, 5.0, 6.1, 8.8, 5.1, 9.8, 4.3, 4.0, 8.2],
          [2.1, 5.3, 7.0, 6.3, 7.8, 5.5, 6.1, 3.7, 9.2, 6.8],
          [3.1, 2.4, 6.1, 8.2, 5.3, 6.4, 5.0, 6.9, 0.7, 0.5],
          [4.2, 8.7, 1.9, 4.1, 9.6, 6.7, 8.9, 8.6, 8.3, 1.9]]

#isi weights mengikuti inputs dan neuronnya
weights = [[1.3, 3.7, 3.3, 9.9, -8.9, 4.8, 3.7, 6.9, 5.3, 5.6],
           [0.25, 5.8, 1.9, 2.7, 1.3, 0.7, 7.3, 1.0, 7.9, 8.9],
           [7.4, 8.2, 5.6, -2.7, 5.1, 8.3, 1.9, 9.3, 3.2, 7.8],
           [6.7, 5.1, 3.2, 6.7, 9.1, 9.3, 8.2, 7.8, -6.5, 4.8],
           [6.3, 1.0, 6.3, -4.8, 2.3, 7.2, 9.1, 6.7, 9.4, 9.9]]

#penggunaan bias untuk neuronnya
biases = [7.8, 6.4, 3.9, 2.2, 9.8]

#proses penghitungan output
layer_outputs = np.dot(inputs, np.array(weights).T) + biases

#pemanggilan ouput
print(layer_outputs)